services:
  - type: web
    name: nexacrm-api
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RESEND_API
        sync: false
      - key: PUBLIC_SERVER_FILE
        sync: false
      - key: PORT
        value: 10000
